apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grpc.name }}
  labels:
    app: {{ .Values.grpc.name }}
    component: grpc
    project: {{ .Values.projectCode }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grpc.name }}
      component: grpc
  template:
    metadata:
      labels:
        app: {{ .Values.grpc.name }}
        component: grpc
        project: {{ .Values.projectCode }}
    spec:
      containers:
        - name: grpc-container
          image: "{{ .Values.images.grpc.repository }}:{{ .Values.images.grpc.tag }}"
          imagePullPolicy: {{ .Values.images.grpc.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.grpc.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grpc.name }}
  labels:
    app: {{ .Values.grpc.name }}
    component: grpc
    project: {{ .Values.projectCode }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.grpc.name }}
    component: grpc
  ports:
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: grpc
