replicaCount: 2
image:
  repository: products-s06
  tag: "latest"
service:
  type: NodePort
  port: 80
  targetPort: 8143
resources:
  requests: 
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"