events {}

http {
    server {
        listen 8080;

        location /api/events {
            proxy_pass http://events-svc:8257;
        }

        location /health {
            proxy_pass http://events-svc:8257;
        }
    }
}
